package edu.gemini.seqexec.model

import edu.gemini.seqexec.model.dhs.ObsId

/**
  * Events that maybe generated by the seqexec. This is very generic and includes e.g. a step execution, stops, etc
  */
sealed trait SeqexecEvent
case object NullEvent extends SeqexecEvent
case object SeqexecConnectionOpenEvent extends SeqexecEvent
case object SeqexecConnectionCloseEvent extends SeqexecEvent
case class SeqexecConnectionError(e: String) extends SeqexecEvent
case class SequenceStartEvent(id: String) extends SeqexecEvent
case class SequenceCompletedEvent(id: String) extends SeqexecEvent
case class StepExecutedEvent(id: String, completed: Int, remaining: Int, fileId: ObsId) extends SeqexecEvent