#
#  Run Seqexec locally in docker
#
#  -- on host --
#  docker build -t registry.gitlab.com/nsf-noirlab/gemini/rtsw/user-tools/seqexec-tester/seqexec-base -f Dockerfile.base .

FROM ubuntu:22.04

# Environment variables
ENV SCALA_VERSION=2.13.8 \
    SBT_VERSION=1.6.2 \
    JAVA_VERSION=17 \
    JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/ \
    PATH=$JAVA_HOME/bin:$PATH

# Install system packages
RUN apt-get update && apt-get install -y \
    wget \
    tree \
    htop \
    zip \
    unzip \
    lsb-core \
    software-properties-common \
    sudo \
    curl \
    vim \
    npm

# Install Java 17
RUN add-apt-repository -y ppa:openjdk-r/ppa && \
    apt-get update && \
    apt-get install -y openjdk-17-jdk

# Install Scala and SBT
RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list && \
    curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add - && \
    apt-get update && \
    apt-get install -y scala sbt

# Cleanup
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /*.deb

CMD ["/sbin/my_init"]

