package edu.gemini.seqexec.server

/**
  * Events that maybe generated by the seqexec. This is very generic and includes e.g. a step execution, stops, etc
  */
sealed trait SeqexecEvent
case object NullEvent extends SeqexecEvent
case class StepExecuted(s: String) extends SeqexecEvent